name: 'child'
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      random_value:
        required: true
        type: string

    secrets:
      random_secret:
        required: true

jobs:
  child:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Print values
        id: print
        run: |
          echo ${{ vars.RANDOM_VALUE }}
          echo ${{ inputs.random_value }}
          echo ${{ secrets.random_secret }}
