name: content-api

# This workflow is triggered on push to the 'content-web' directory of the  main branch of the repository
on:
  push:
    branches:
    - main
    paths:
    - 'content-api/**'
    # - api.deployment.yml
    # - api.service.yml

  # Configure workflow to also support triggering manually
  workflow_dispatch:

# Environment variables are defined so that they can be used throughout the job definitions.
env:
  imageRepository: 'content-api'
  resourceGroupName: 'Fabmedical-605450605450'
  clusterName: 'fabmedical-605450605450'
  containerRegistryName: 'fabmedical605450605450'
  containerRegistry: 'fabmedical605450605450.azurecr.io'
  dockerfilePath: './content-api'
  tag: '${{ github.run_id  }}'

# Jobs define the actions that take place when code is pushed to the main branch
jobs:
  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@master
  deployment-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: deploy
      run: echo 'Deploying dev'
  deployment-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: deploy
      run: echo 'Deploying test'
  deployment-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: deploy
      run: echo 'Deploying prod'
